export const tarpCopy = {
  en: {
    eyebrow: "Tetiaroa Atoll Restoration Program",
    title: "Help the island recover.",
    intro:
      "A claw in the leaf litter. A wing above the sand. Remove the rats and yellow crazy ants, and discover how many lives share this small stretch of island.",
    startTitle: "Look closely at the motu.",
    startBody:
      "Look among the trees and along the sand. Tap the rats and yellow crazy ants to remove them, then watch the island change.",
    start: "Explore the island",
    loading: "Finding our way to the motu…",
    error: "The island couldn’t load. Let’s try again.",
    retry: "Try again",
    sceneLabel:
      "A Tetiaroa island. Remove rats and yellow crazy ant colonies to reveal native plants, land crabs, boobies, and terns.",
    progressLabel: "Removed",
    reset: "Start over",
    pause: "Pause exploration",
    resume: "Resume exploration",
    pauseHint: "Take a moment. The island will wait.",
    panHint: "Drag to look around the island.",
    panLeft: "Look left across the island",
    panRight: "Look right across the island",
    firstHint: "Tap a rat or a cluster of yellow ants.",
    ratRemoved: "One less rat. Keep looking among the leaves.",
    antsRemoved: "This patch is clear of ants. Keep exploring.",
    completeTitle: "Look who’s back.",
    completeBody:
      "The birds bring the sea home with them. Their droppings feed the soil, and water carries some of those nutrients toward the lagoon. TARP follows this connection from nesting grounds to coral reefs.",
    explore: "Meet the island’s wildlife",
    close: "Back to the island",
    guideLabel: "In our species guide",
    removeRat: "Remove rat",
    removeAnts: "Remove yellow crazy ant colony",
    ratsLabel: "Rats removed",
    antsLabel: "Colonies removed",
    returningLabel: "Life returning",
    replay: "Explore again",
    learnMore: "Follow TARP’s work",
  },
  fr: {
    eyebrow: "Programme de restauration de l’atoll de Tetiaroa",
    title: "Aidez le motu à revivre.",
    intro:
      "Une pince sous les feuilles. Une aile au-dessus du sable. Retirez les rats et les fourmis folles jaunes, puis découvrez tous ceux qui partagent ce petit bout d’île.",
    startTitle: "Regardez le motu de plus près.",
    startBody:
      "Cherchez entre les arbres et sur le sable. Touchez les rats et les fourmis folles jaunes pour les retirer, puis regardez le motu changer.",
    start: "Explorer le motu",
    loading: "En route vers le motu…",
    error: "Le motu n’a pas pu s’afficher. Réessayons.",
    retry: "Réessayer",
    sceneLabel:
      "Un motu de Tetiaroa. Retirez les rats et les colonies de fourmis folles jaunes pour voir revenir plantes indigènes, crabes terrestres, fous et sternes.",
    progressLabel: "Retirés",
    reset: "Recommencer",
    pause: "Mettre l’exploration en pause",
    resume: "Reprendre l’exploration",
    pauseHint: "Prenez votre temps. Le motu vous attend.",
    panHint: "Faites glisser la vue pour explorer le motu.",
    panLeft: "Regarder vers la gauche du motu",
    panRight: "Regarder vers la droite du motu",
    firstHint: "Touchez un rat ou un groupe de fourmis jaunes.",
    ratRemoved: "Un rat de moins. Cherchez encore entre les feuilles.",
    antsRemoved: "Les fourmis ont quitté ce coin. Poursuivez l’exploration.",
    completeTitle: "Regardez qui est revenu.",
    completeBody:
      "Les oiseaux rapportent un peu de l’océan à terre. Leurs fientes nourrissent le sol, puis l’eau entraîne une partie de ces nutriments vers le lagon. Le TARP suit ce chemin, des lieux de nidification jusqu’aux récifs coralliens.",
    explore: "Rencontrer les habitants du motu",
    close: "Retour au motu",
    guideLabel: "Dans notre guide des espèces",
    removeRat: "Retirer le rat",
    removeAnts: "Retirer la colonie de fourmis folles jaunes",
    ratsLabel: "Rats retirés",
    antsLabel: "Colonies retirées",
    returningLabel: "La vie revient",
    replay: "Explorer à nouveau",
    learnMore: "Suivre le travail du TARP",
  },
} as const;

export const nativeLife = [
  {
    id: "seedling",
    image: "native-seedling.png",
    en: {
      name: "Native seedlings",
      title: "A forest starts close to the ground.",
      body: "A new shoot is easy to miss. Rats eat seeds and young plants; removing them gives native vegetation a chance to grow. Those leaves can become shelter for the island’s next generation of seabirds.",
      guideHref: "/island/plants",
      discoverLabel: "Discover the native seedlings",
      arrivalHint: "New leaves are opening. Tap a seedling to look closer.",
    },
    fr: {
      name: "Jeunes plantes indigènes",
      title: "La forêt commence au ras du sol.",
      body: "Une jeune pousse passe facilement inaperçue. Les rats mangent graines et plantules ; leur retrait permet à la végétation indigène de grandir. Ces feuilles pourront un jour abriter une nouvelle génération d’oiseaux marins.",
      guideHref: "/fr/island/plants",
      discoverLabel: "Découvrir les jeunes plantes indigènes",
      arrivalHint:
        "De nouvelles feuilles s’ouvrent. Touchez une jeune pousse pour l’observer.",
    },
  },
  {
    id: "crab",
    image: "hermit-crab.png",
    en: {
      name: "Strawberry hermit crab",
      title: "That shell is going somewhere.",
      body: "Look for the bright red legs below that borrowed shell. Strawberry hermit crabs eat fallen leaves and other remains along the shore. When invasive ants disappear, native crabs have room to return.",
      guideHref: "/island/invertebrates/strawberry-hermit-crab",
      discoverLabel: "Meet the strawberry hermit crab",
      arrivalHint: "That shell is moving. Tap the red crab beneath it.",
    },
    fr: {
      name: "Bernard-l’ermite fraise",
      title: "Une coquille qui se promène.",
      body: "Repérez les pattes rouge vif sous la coquille. Le bernard-l’ermite fraise se nourrit de feuilles mortes et d’autres débris sur le rivage. Quand les fourmis invasives disparaissent, les crabes indigènes peuvent revenir.",
      guideHref: "/fr/island/invertebrates/strawberry-hermit-crab",
      discoverLabel: "Rencontrer le bernard-l’ermite fraise",
      arrivalHint:
        "Cette coquille bouge. Touchez le crabe rouge qui la porte.",
    },
  },
  {
    id: "tern",
    image: "white-tern.png",
    en: {
      name: "White tern",
      title: "An egg out in the open.",
      body: "White terns lay a single egg right on a branch, without building a nest. With rats gone, more eggs can hatch—and more chicks get the chance to take flight.",
      guideHref: "/island/birds/white-common-tern",
      discoverLabel: "Meet the white tern",
      arrivalHint: "White wings above the trees. Tap a tern to meet it.",
    },
    fr: {
      name: "Gygis blanche",
      title: "Un œuf à découvert.",
      body: "La gygis blanche pond un seul œuf directement sur une branche, sans construire de nid. Sans les rats, davantage d’œufs peuvent éclore et davantage de poussins ont la chance de prendre leur envol.",
      guideHref: "/fr/island/birds/white-common-tern",
      discoverLabel: "Rencontrer la gygis blanche",
      arrivalHint:
        "Des ailes blanches au-dessus des arbres. Touchez une gygis pour la découvrir.",
    },
  },
  {
    id: "coconutCrab",
    image: "coconut-crab.png",
    en: {
      name: "Coconut crab",
      title: "Once, it wore a shell.",
      body: "As a youngster, this forest giant carried a borrowed shell. Now its own armor does the job. Coconut crabs search for food at night, but their lives begin in the sea: females return to the shore to release their larvae.",
      guideHref: "/island/invertebrates/coconut-crab",
      discoverLabel: "Meet the coconut crab",
      arrivalHint: "A forest giant has arrived. Tap the coconut crab.",
    },
    fr: {
      name: "Crabe de cocotier",
      title: "Il a quitté sa coquille.",
      body: "Petit, ce géant de la forêt s’abritait dans une coquille empruntée. L’adulte porte sa propre armure et cherche sa nourriture la nuit. Pourtant, tout commence en mer : la femelle retourne au rivage pour y libérer ses larves.",
      guideHref: "/fr/island/invertebrates/coconut-crab",
      discoverLabel: "Rencontrer le crabe de cocotier",
      arrivalHint:
        "Un géant de la forêt est arrivé. Touchez le crabe de cocotier.",
    },
  },
  {
    id: "ghostCrab",
    image: "horned-ghost-crab.png",
    en: {
      name: "Horned ghost crab",
      title: "Gone before you blink.",
      body: "Those little holes in the beach have an owner. The horned ghost crab slips into a deep burrow to escape heat and drying air. Look for eyes raised on stalks and a pale body that almost disappears against the sand.",
      guideHref: "/island/invertebrates/horned-ghost-crab",
      discoverLabel: "Meet the horned ghost crab",
      arrivalHint: "Eyes above the sand. Tap the ghost crab to look closer.",
    },
    fr: {
      name: "Crabe fantôme cornu",
      title: "Disparu en un clin d’œil.",
      body: "Ces petits trous dans la plage ont un propriétaire. Le crabe fantôme cornu se réfugie dans un terrier profond pour échapper à la chaleur et à l’air sec. Repérez ses yeux dressés et son corps pâle, presque invisible sur le sable.",
      guideHref: "/fr/island/invertebrates/horned-ghost-crab",
      discoverLabel: "Rencontrer le crabe fantôme cornu",
      arrivalHint:
        "Des yeux dépassent du sable. Touchez le crabe fantôme pour l’observer.",
    },
  },
  {
    id: "booby",
    image: "brown-booby.png",
    en: {
      name: "Brown booby",
      title: "The nest is down here.",
      body: "A brown booby plunges into the sea, then pursues fish underwater with its wings and webbed feet. Back on the motu, it nests on the ground. Both parents take turns tending the egg and feeding their chick.",
      guideHref: "/island/birds/brown-booby",
      discoverLabel: "Meet the brown booby",
      arrivalHint: "A seabird settles on the sand. Tap the brown booby.",
    },
    fr: {
      name: "Fou brun",
      title: "Le nid est ici, au sol.",
      body: "Le fou brun plonge dans la mer, puis poursuit les poissons sous l’eau à l’aide de ses ailes et de ses pattes palmées. Sur le motu, il niche au sol. Les deux parents se relaient pour couver et nourrir leur poussin.",
      guideHref: "/fr/island/birds/brown-booby",
      discoverLabel: "Rencontrer le fou brun",
      arrivalHint: "Un oiseau marin se pose sur le sable. Touchez le fou brun.",
    },
  },
  {
    id: "sootyTern",
    image: "sooty-tern.png",
    en: {
      name: "Sooty tern",
      title: "One egg. A hollow in the sand.",
      body: "The sooty tern spends much of its life far out at sea. Raising a chick brings it back to land: one speckled egg in a shallow scrape, with both parents sharing the work. On Tetiaroa, it nests on Tahuna Iti.",
      guideHref: "/island/birds/sooty-tern",
      discoverLabel: "Meet the sooty tern",
      arrivalHint: "An ocean traveller comes ashore. Tap the sooty tern.",
    },
    fr: {
      name: "Sterne fuligineuse",
      title: "Un œuf dans un creux du sable.",
      body: "La sterne fuligineuse passe une grande partie de sa vie au large. Élever un poussin la ramène à terre : un œuf tacheté dans un léger creux, et deux parents qui partagent le travail. À Tetiaroa, elle niche sur Tahuna Iti.",
      guideHref: "/fr/island/birds/sooty-tern",
      discoverLabel: "Rencontrer la sterne fuligineuse",
      arrivalHint:
        "Une voyageuse du large rejoint le rivage. Touchez la sterne fuligineuse.",
    },
  },
] as const;

export type NativeLifeId = (typeof nativeLife)[number]["id"];
