import type { PillarLocale } from "./pillar-content";

export function getEducationActivitiesPath(locale: PillarLocale) {
  return `${locale === "fr" ? "/fr" : ""}/pillars/education-culture/activities`;
}

export const educationActivitiesCopy = {
  en: {
    title: "Educational activities",
    metadataDescription: "Discover Lagoon School with The Brando. With the Junior Naturalist passport, kids collect stamps and earn free Tetiaroa Society swag when their collection is complete.",
    parentLabel: "Education + Culture",
    breadcrumbLabel: "Breadcrumb",
    eyebrow: "Young explorers welcome",
    heroTitle: "What lives\nhere?",
    heroCopy: "On Tetiaroa, a fish in the shallows can start a hundred questions. Lagoon School and the Junior Naturalist passport give curious kids ways to look closer.",
    heroImageAlt: "Young people learning in the shallow lagoon on Tetiaroa, with an instructor on the shore",
    heroCaption: "Learning on Tetiaroa",
    lagoonJump: "Discover Lagoon School",
    passportJump: "The Junior Naturalist passport",
    lagoon: {
      eyebrow: "Learn with the island",
      title: "Lagoon School",
      partner: "In partnership with The Brando",
      lead: "The best questions start with something you’ve just seen.",
      copy: "What’s that fish? How does this plant grow here? At Lagoon School, young guests of The Brando explore Tetiaroa’s marine life, plants, and sea turtles with Tetiaroa Society guides. There’s plenty to learn when you stop and look.",
      themes: [
        { title: "Below the surface", copy: "Explore the lagoon and get to know its marine life." },
        { title: "Along the forest path", copy: "Look closely at the plants growing all around you." },
        { title: "Into a turtle’s world", copy: "Learn about sea turtles and their place in the life of Tetiaroa." },
      ],
      action: "Ask about Lagoon School",
      partnerAction: "Lagoon School at The Brando",
    },
    passport: {
      eyebrow: "A little book. A lot to discover.",
      title: "Junior Naturalist\npassport",
      lead: "Every stamp has a story.",
      copy: "A stamp for a new discovery. A page to show everyone back home. The Junior Naturalist passport lets kids build a collection as they complete educational activities on Tetiaroa.",
      bookTitle: "Junior\nNaturalist",
      bookLabel: "Passport",
      bookFooter: "Tetiaroa Society",
      steps: [
        { title: "Take a closer look", copy: "Join in the Junior Naturalist activities and get to know the atoll." },
        { title: "Build your stamp collection", copy: "Complete activities and collect stamps in your passport book." },
        { title: "Finish the collection. Get the swag.", copy: "Kids who complete their stamp collection receive free Tetiaroa Society swag." },
      ],
      reward: "Full passport. Free swag.",
      rewardCopy: "A thank-you for seeing the collection through, with something to take home alongside the stories.",
    },
    visit: {
      eyebrow: "Bring your questions",
      title: "Their next question starts here.",
      copy: "Planning a visit with children? Get in touch about Lagoon School, the Junior Naturalist passport, and how to take part during your stay.",
      action: "Ask about activities",
      back: "Back to Education + Culture",
    },
    feature: {
      eyebrow: "For children who want to know more",
      title: "What will they spot first?",
      copy: "Get to know Tetiaroa through Lagoon School, in partnership with The Brando. Or start a Junior Naturalist passport: kids who complete their stamp collection receive free Tetiaroa Society swag.",
      action: "Explore educational activities",
    },
  },
  fr: {
    title: "Activités éducatives",
    metadataDescription: "Découvrez la Lagoon School avec The Brando. Avec le passeport Junior Naturalist, les enfants complètent leur collection de tampons et reçoivent des cadeaux Tetiaroa Society.",
    parentLabel: "Éducation + Culture",
    breadcrumbLabel: "Fil d’Ariane",
    eyebrow: "Bienvenue aux jeunes explorateurs",
    heroTitle: "Qui vit\nici ?",
    heroCopy: "À Tetiaroa, un poisson près du rivage suffit à faire naître cent questions. La Lagoon School et le passeport Junior Naturalist invitent les enfants à regarder d’un peu plus près.",
    heroImageAlt: "Des jeunes découvrent le lagon de Tetiaroa dans l’eau peu profonde, accompagnés d’un guide sur le rivage",
    heroCaption: "Apprendre à Tetiaroa",
    lagoonJump: "Découvrir la Lagoon School",
    passportJump: "Passeport Junior Naturalist",
    lagoon: {
      eyebrow: "Apprendre avec l’île",
      title: "Lagoon School",
      partner: "En partenariat avec The Brando",
      lead: "Il suffit parfois d’un regard pour avoir mille questions.",
      copy: "Quel est ce poisson ? Comment cette plante pousse-t-elle ici ? À la Lagoon School, les jeunes hôtes du Brando découvrent la vie marine, les plantes et les tortues de Tetiaroa avec les guides de Tetiaroa Society. On apprend tant de choses en prenant le temps d’observer.",
      themes: [
        { title: "Sous la surface", copy: "Explorer le lagon et faire connaissance avec sa vie marine." },
        { title: "Au fil des sentiers", copy: "Observer de près les plantes qui poussent tout autour de soi." },
        { title: "Dans le monde des tortues", copy: "Découvrir les tortues marines et leur place dans la vie de Tetiaroa." },
      ],
      action: "Parlons de la Lagoon School",
      partnerAction: "La Lagoon School au Brando",
    },
    passport: {
      eyebrow: "Un petit carnet. Mille choses à découvrir.",
      title: "Le passeport\nJunior Naturalist",
      lead: "Chaque tampon a son histoire.",
      copy: "Un tampon pour une découverte. Une page à montrer une fois rentré à la maison. Avec le passeport Junior Naturalist, les enfants agrandissent leur collection au fil des activités éducatives à Tetiaroa.",
      bookTitle: "Junior\nNaturalist",
      bookLabel: "Passeport",
      bookFooter: "Tetiaroa Society",
      steps: [
        { title: "Regarder d’un peu plus près", copy: "Participer aux activités Junior Naturalist et faire connaissance avec l’atoll." },
        { title: "Collectionner les tampons", copy: "Accomplir les activités et recevoir des tampons dans son passeport." },
        { title: "Collection complète, cadeau à la clé.", copy: "Les enfants qui complètent leur collection de tampons reçoivent des cadeaux Tetiaroa Society, offerts pour l’occasion." },
      ],
      reward: "Passeport rempli. Cadeau offert.",
      rewardCopy: "De quoi les remercier d’être allés jusqu’au bout, avec un souvenir à rapporter et des histoires à raconter.",
    },
    visit: {
      eyebrow: "Venez avec vos questions",
      title: "Leur prochaine question commence ici.",
      copy: "Vous préparez un séjour avec des enfants ? Contactez-nous pour en savoir plus sur la Lagoon School, le passeport Junior Naturalist et les possibilités de participation pendant votre séjour.",
      action: "Parlons des activités",
      back: "Retour à Éducation + Culture",
    },
    feature: {
      eyebrow: "Pour les enfants qui veulent tout savoir",
      title: "Que vont-ils repérer en premier ?",
      copy: "Découvrez Tetiaroa avec la Lagoon School, en partenariat avec The Brando. Ou commencez un passeport Junior Naturalist : les enfants qui complètent leur collection de tampons reçoivent des cadeaux Tetiaroa Society.",
      action: "Découvrir les activités",
    },
  },
} as const;
