export type Cohort =
  | "On-island team"
  | "Board of Directors"
  | "Scientific Advisory Board";

export type Person = {
  id: string;
  name: string;
  role: string;
  cohort: Cohort;
  image: string;
  href: string;
  summary: string;
  focus: string[];
  featured?: boolean;
};

const teamImage = (id: string) => `/team/${id}.webp`;
const profile = (path: string) => path;

const staffSummary =
  "Keeps the daily work of the atoll moving across conservation, education, visitor learning, and field operations.";
const boardSummary =
  "Provides governance, institutional memory, and cross-sector stewardship for Tetiaroa Society's long-term resilience.";
const advisorySummary =
  "Advises the science program so field observations, restoration choices, and research partnerships stay rigorous.";

export const people: Person[] = [
  {
    id: "tj-tate",
    name: "Tj Tate",
    role: "Chief Executive Officer",
    cohort: "On-island team",
    image: teamImage("tj-tate"),
    href: profile("/tj-tate"),
    summary:
      "Leads the society's next chapter, connecting field work, partnerships, education, and donor support into one operating rhythm.",
    focus: ["Leadership", "Partnerships", "Strategy"],
    featured: true,
  },
  {
    id: "julien-castel",
    name: "Julien Castel",
    role: "Chief Financial Officer",
    cohort: "On-island team",
    image: teamImage("julien-castel"),
    href: profile("/julien-castel"),
    summary: "Bio forthcoming.",
    focus: ["Leadership", "Finance"],
  },
  {
    id: "jayna-devore",
    name: "Dr. Jayna DeVore",
    role: "Director of Conservation, Science & Education",
    cohort: "On-island team",
    image: teamImage("jayna-devore"),
    href: profile("/dr-jayna-devore"),
    summary: "Bio forthcoming.",
    focus: ["Leadership", "Conservation", "Science", "Education"],
  },
  {
    id: "giulia-mouly",
    name: "Giulia Mouly",
    role: "Director of Operations",
    cohort: "On-island team",
    image: teamImage("giulia-mouly"),
    href: profile("/giulia-mouly"),
    summary:
      "Connects people, place, and purpose through field station operations, hospitality, partnerships, and sustainability.",
    focus: ["Operations", "Bailey Field Station", "Partnerships"],
  },
  {
    id: "hinanui-robson",
    name: "Hinanui Joan Robson",
    role: "Science and Conservation Coordinator",
    cohort: "On-island team",
    image: teamImage("hinanui-robson"),
    href: profile("/hinanui-robson"),
    summary:
      "Coordinates research activity on the atoll, helping field teams, visiting scientists, and local knowledge meet cleanly.",
    focus: ["Science", "Research", "Field operations"],
    featured: true,
  },
  {
    id: "tihoni-maire",
    name: "Tihoni Maire",
    role: "Chief Naturalist",
    cohort: "On-island team",
    image: teamImage("tihoni-maire"),
    href: profile("/tihoni-maire"),
    summary:
      "Leads guide experiences that translate the atoll's wildlife, history, and conservation work for visitors.",
    focus: ["Guides", "Culture", "Visitor learning"],
    featured: true,
  },
  {
    id: "vaitea-izal",
    name: "Vaitea Izal",
    role: "Bailey Field Station Manager",
    cohort: "On-island team",
    image: teamImage("vaitea-izal"),
    href: profile("/vaitea-izal"),
    summary:
      "Keeps the Ecostation ready for the researchers, students, and partners who turn the atoll into a living laboratory.",
    focus: ["Ecostation", "Operations", "Research"],
    featured: true,
  },
  {
    id: "hereiti-lelong",
    name: "Elena Hereiti Lelong",
    role: "Communications Manager",
    cohort: "On-island team",
    image: teamImage("hereiti-lelong"),
    href: profile("/hereiti-lelong"),
    summary:
      "Shapes the public story of the work, from field updates and education moments to the society's wider voice.",
    focus: ["Communications", "Storytelling", "Community"],
  },
  {
    id: "ngnahina-moua",
    name: "Ngnahina Moua",
    role: "Education & Cultural Coordinator",
    cohort: "On-island team",
    image: teamImage("ngnahina-moua"),
    href: profile("/ngnahina-moua"),
    summary:
      "Builds education and cultural programs that connect Polynesian students with Polynesian science and stewardship.",
    focus: ["Education", "Culture", "Community"],
    featured: true,
  },
  {
    id: "kealoha-wilkes",
    name: "Kealoha Wilkes",
    role: "Naturalist",
    cohort: "On-island team",
    image: teamImage("kealoha-wilkes"),
    href: profile("/kealoha-wilkes"),
    summary: staffSummary,
    focus: ["Guides", "Visitor learning", "Culture"],
  },
  {
    id: "hugo-torres",
    name: "Hugo Torres",
    role: "Naturalist",
    cohort: "On-island team",
    image: teamImage("hugo-torres"),
    href: profile("/hugo-torres"),
    summary: staffSummary,
    focus: ["Guides", "Visitor learning", "Field operations"],
  },
  {
    id: "hina-patii",
    name: "Hina Patii",
    role: "Naturalist",
    cohort: "On-island team",
    image: teamImage("hina-patii"),
    href: profile("/hina-patii"),
    summary: staffSummary,
    focus: ["Guides", "Visitor learning", "Culture"],
  },
  {
    id: "tekura-ung",
    name: "Tekura Ung",
    role: "Naturalist",
    cohort: "On-island team",
    image: teamImage("tekura-ung"),
    href: profile("/tekura-ung"),
    summary: staffSummary,
    focus: ["Guides", "Visitor learning", "Culture"],
  },
  {
    id: "thierry-sommer",
    name: "Thierry Sommer",
    role: "Naturalist",
    cohort: "On-island team",
    image: teamImage("thierry-sommer"),
    href: profile("/thierry-sommer"),
    summary: staffSummary,
    focus: ["Guides", "Visitor learning", "Field operations"],
  },
  {
    id: "maxime-courroux",
    name: "Maxime Courroux",
    role: "Naturalist",
    cohort: "On-island team",
    image: teamImage("maxime-courroux"),
    href: profile("/maxime-courroux"),
    summary: staffSummary,
    focus: ["Guides", "Visitor learning", "Field operations"],
  },
  {
    id: "romain-clervoy",
    name: "Romain Clervoy",
    role: "Dive Operations Manager",
    cohort: "On-island team",
    image: teamImage("romain-clervoy"),
    href: profile("/romain-clervoy"),
    summary:
      "Oversees dive operations that help people encounter the reef while respecting the atoll's rules and rhythms.",
    focus: ["Dive operations", "Safety", "Visitor learning"],
    featured: true,
  },
  {
    id: "lusiano-kolokilagi",
    name: "Lusiano Kolokilagi",
    role: "Ranger",
    cohort: "On-island team",
    image: teamImage("lusiano-kolokilagi"),
    href: profile("/lusiano-kolokilagi"),
    summary: staffSummary,
    focus: ["Rangers", "Field operations", "Conservation"],
  },
  {
    id: "tuterai-apuarii",
    name: "Tuterai Apuarii",
    role: "Ranger",
    cohort: "On-island team",
    image: teamImage("tuterai-apuarii"),
    href: profile("/tuterai-apuarii"),
    summary: staffSummary,
    focus: ["Rangers", "Field operations", "Conservation"],
  },
  {
    id: "jean-paul-chongue",
    name: "Jean Paul Chongue",
    role: "Ranger",
    cohort: "On-island team",
    image: teamImage("jean-paul-chongue"),
    href: profile("/jean-paul-chongue"),
    summary: staffSummary,
    focus: ["Rangers", "Field operations", "Conservation"],
  },
  {
    id: "carol-ann-raydon",
    name: "Carol Ann Raydon",
    role: "Web Designer/Developer",
    cohort: "On-island team",
    image: teamImage("carol-ann-raydon"),
    href: profile("/carol-ann-raydon"),
    summary: staffSummary,
    focus: ["Digital", "Communications", "Storytelling"],
  },
  {
    id: "david-seeley",
    name: "David Seeley",
    role: "Treasurer",
    cohort: "Board of Directors",
    image: teamImage("david-seeley"),
    href: profile("/david-seeley"),
    summary: boardSummary,
    focus: ["Governance", "Strategy", "Stewardship"],
  },
  {
    id: "neil-davies-board",
    name: "Neil Davies",
    role: "Board Member",
    cohort: "Board of Directors",
    image: teamImage("neil-davies-board"),
    href: profile("/neil-davies"),
    summary: boardSummary,
    focus: ["Governance", "Science", "Research"],
  },
  {
    id: "stan-rowland",
    name: "Stan Rowland",
    role: "Secretary",
    cohort: "Board of Directors",
    image: teamImage("stan-rowland"),
    href: profile("/stan-rowland"),
    summary: boardSummary,
    focus: ["Governance", "Stewardship", "Strategy"],
  },
  {
    id: "cecile-gaspar-board",
    name: "Cecile Gaspar",
    role: "Board Member",
    cohort: "Board of Directors",
    image: teamImage("cecile-gaspar-board"),
    href: profile("/cecile-gaspar"),
    summary: boardSummary,
    focus: ["Governance", "Conservation", "Science"],
  },
  {
    id: "ed-begley",
    name: "Ed Begley",
    role: "Board Member",
    cohort: "Board of Directors",
    image: teamImage("ed-begley"),
    href: profile("/ed-begley"),
    summary: boardSummary,
    focus: ["Governance", "Advocacy", "Stewardship"],
  },
  {
    id: "richard-bailey",
    name: "Richard Bailey",
    role: "Board Chairman",
    cohort: "Board of Directors",
    image: teamImage("richard-bailey"),
    href: profile("/richard-bailey"),
    summary: boardSummary,
    focus: ["Governance", "Partnerships", "Stewardship"],
  },
  {
    id: "larry-dressler",
    name: "Larry Dressler",
    role: "Board Member",
    cohort: "Board of Directors",
    image: teamImage("larry-dressler"),
    href: profile("/larry-dressler"),
    summary: boardSummary,
    focus: ["Governance", "Strategy", "Stewardship"],
  },
  {
    id: "avra-douglas",
    name: "Avra Douglas",
    role: "Board Member",
    cohort: "Board of Directors",
    image: teamImage("avra-douglas"),
    href: profile("/avra-douglas"),
    summary: boardSummary,
    focus: ["Governance", "Community", "Stewardship"],
  },
  {
    id: "mike-medavoy",
    name: "Mike Medavoy",
    role: "Board Member",
    cohort: "Board of Directors",
    image: teamImage("mike-medavoy"),
    href: profile("/mike-medavoy"),
    summary: boardSummary,
    focus: ["Governance", "Storytelling", "Advocacy"],
  },
  {
    id: "daniel-kammen-board",
    name: "Daniel Kammen",
    role: "Board Member",
    cohort: "Board of Directors",
    image: teamImage("daniel-kammen-board"),
    href: profile("/daniel-kammen"),
    summary: boardSummary,
    focus: ["Governance", "Climate", "Science"],
  },
  {
    id: "benjamin-anderson",
    name: "Benjamin Anderson",
    role: "Board Member",
    cohort: "Board of Directors",
    image: teamImage("benjamin-anderson"),
    href: profile("/benjamin-anderson"),
    summary: boardSummary,
    focus: ["Governance", "Strategy", "Partnerships"],
  },
  {
    id: "costas-christ",
    name: "Costas Christ",
    role: "Board Member",
    cohort: "Board of Directors",
    image: teamImage("costas-christ"),
    href: profile("/costas-christ"),
    summary: boardSummary,
    focus: ["Governance", "Sustainable travel", "Stewardship"],
  },
  {
    id: "hinano-murphy",
    name: "Hinano Murphy",
    role: "Board Member",
    cohort: "Board of Directors",
    image: teamImage("hinano-murphy"),
    href: profile("/hinano-murphy"),
    summary: boardSummary,
    focus: ["Governance", "Culture", "Education"],
  },
  {
    id: "carl-swanes",
    name: "Carl Swanes",
    role: "Board Member",
    cohort: "Board of Directors",
    image: teamImage("carl-swanes"),
    href: profile("/carl-swanes"),
    summary: boardSummary,
    focus: ["Governance", "Strategy", "Stewardship"],
  },
  {
    id: "rebecca-brando",
    name: "Rebecca Brando",
    role: "Board Member",
    cohort: "Board of Directors",
    image: teamImage("rebecca-brando"),
    href: profile("/rebecca-brando"),
    summary: boardSummary,
    focus: ["Governance", "Legacy", "Stewardship"],
  },
  {
    id: "rick-hess",
    name: "Rick Hess",
    role: "Board Member",
    cohort: "Board of Directors",
    image: teamImage("rick-hess"),
    href: profile("/rick-hess"),
    summary: boardSummary,
    focus: ["Governance", "Strategy", "Stewardship"],
  },
  {
    id: "susan-neisloss",
    name: "Susan Neisloss",
    role: "Vice Chair",
    cohort: "Board of Directors",
    image: teamImage("susan-neisloss"),
    href: profile("/susan-neisloss"),
    summary: boardSummary,
    focus: ["Governance", "Advocacy", "Stewardship"],
  },
  {
    id: "heather-grenier",
    name: "Heather Grenier",
    role: "Board Member",
    cohort: "Board of Directors",
    image: teamImage("heather-grenier"),
    href: profile("/heather-grenier"),
    summary: boardSummary,
    focus: ["Governance", "Partnerships", "Stewardship"],
  },
  {
    id: "michael-v-lewis",
    name: "Michael V Lewis",
    role: "Board Member",
    cohort: "Board of Directors",
    image: teamImage("michael-v-lewis"),
    href: profile("/michael-v-lewis"),
    summary: boardSummary,
    focus: ["Governance", "Strategy", "Partnerships"],
  },
  {
    id: "neil-davies-advisory",
    name: "Neil Davies",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: teamImage("neil-davies-advisory"),
    href: profile("/neil-davies"),
    summary: advisorySummary,
    focus: ["Science", "Research", "Advisory"],
  },
  {
    id: "sylvia-earle",
    name: "Sylvia Earle",
    role: "Scientific Advisor Emeritus",
    cohort: "Scientific Advisory Board",
    image: teamImage("sylvia-earle"),
    href: profile("/sylvia-earle"),
    summary: advisorySummary,
    focus: ["Ocean science", "Advisory", "Conservation"],
  },
  {
    id: "billie-swalla",
    name: "Billie Swalla",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: teamImage("billie-swalla"),
    href: profile("/billie-swalla"),
    summary: advisorySummary,
    focus: ["Science", "Research", "Advisory"],
  },
  {
    id: "annaig-le-guen",
    name: "Annaig Le Guen",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: teamImage("annaig-le-guen"),
    href: profile("/annaig-le-guen"),
    summary: advisorySummary,
    focus: ["Culture", "Research", "Advisory"],
  },
  {
    id: "benoit-stoll",
    name: "Benoit Stoll",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: teamImage("benoit-stoll"),
    href: profile("/benoit-stoll"),
    summary: advisorySummary,
    focus: ["Science", "Research", "Advisory"],
  },
  {
    id: "beth-gardner",
    name: "Beth Gardner",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: teamImage("beth-gardner"),
    href: profile("/beth-gardner"),
    summary: advisorySummary,
    focus: ["Science", "Research", "Advisory"],
  },
  {
    id: "cecile-gaspar-advisory",
    name: "Cecile Gaspar",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: teamImage("cecile-gaspar-advisory"),
    href: profile("/cecile-gaspar"),
    summary: advisorySummary,
    focus: ["Conservation", "Science", "Advisory"],
  },
  {
    id: "chris-meyer",
    name: "Chris Meyer",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: teamImage("chris-meyer"),
    href: profile("/chris-meyer"),
    summary: advisorySummary,
    focus: ["Biodiversity", "Research", "Advisory"],
  },
  {
    id: "daniel-kammen-advisory",
    name: "Daniel Kammen",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: teamImage("daniel-kammen-advisory"),
    href: profile("/daniel-kammen"),
    summary: advisorySummary,
    focus: ["Climate", "Energy", "Advisory"],
  },
  {
    id: "guillaume-molle",
    name: "Guillaume Molle",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: teamImage("guillaume-molle"),
    href: profile("/guillaume-molle"),
    summary: advisorySummary,
    focus: ["Culture", "Research", "Advisory"],
  },
  {
    id: "herve-bossin",
    name: "Herve Bossin",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: teamImage("herve-bossin"),
    href: profile("/herve-boissin"),
    summary: advisorySummary,
    focus: ["Biosecurity", "Research", "Advisory"],
  },
  {
    id: "hillary-young",
    name: "Hillary Young",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: teamImage("hillary-young"),
    href: profile("/hillary-young"),
    summary: advisorySummary,
    focus: ["Ecology", "Research", "Advisory"],
  },
  {
    id: "james-russell",
    name: "James Russell",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: teamImage("james-russell"),
    href: profile("/james-russell"),
    summary: advisorySummary,
    focus: ["Restoration", "Research", "Advisory"],
  },
  {
    id: "jean-yves-meyer",
    name: "Jean-Yves Hiro Meyer",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: teamImage("jean-yves-meyer"),
    href: profile("/jean-yves-meyer"),
    summary: advisorySummary,
    focus: ["Botany", "Research", "Advisory"],
  },
  {
    id: "judy-lemus",
    name: "Judy Lemus",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: teamImage("judy-lemus"),
    href: profile("/judy-lemus"),
    summary: advisorySummary,
    focus: ["Education", "Research", "Advisory"],
  },
  {
    id: "mayalen-zubia",
    name: "Mayalen Zubia",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: teamImage("mayalen-zubia"),
    href: profile("/mayalen-zubia"),
    summary: advisorySummary,
    focus: ["Marine ecology", "Research", "Advisory"],
  },
  {
    id: "patrick-kirch",
    name: "Patrick Kirch",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: teamImage("patrick-kirch"),
    href: profile("/patrick-kirch"),
    summary: advisorySummary,
    focus: ["Culture", "Research", "Advisory"],
  },
  {
    id: "robert-carpenter",
    name: "Robert Carpenter",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: teamImage("robert-carpenter"),
    href: profile("/robert-carpenter"),
    summary: advisorySummary,
    focus: ["Marine ecology", "Research", "Advisory"],
  },
  {
    id: "yadvinder-malhi",
    name: "Yadvinder Malhi",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: teamImage("yadvinder-malhi"),
    href: profile("/yadvinder-malhi"),
    summary: advisorySummary,
    focus: ["Climate", "Ecology", "Advisory"],
  },
  {
    id: "ruth-gates",
    name: "Ruth Gates",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: teamImage("ruth-gates"),
    href: profile("/ruth-gates"),
    summary: advisorySummary,
    focus: ["Coral", "Research", "Advisory"],
  },
  {
    id: "serge-planes",
    name: "Serge Planes",
    role: "Scientific Advisor Emeritus",
    cohort: "Scientific Advisory Board",
    image: teamImage("serge-planes"),
    href: profile("/serge-planes"),
    summary: advisorySummary,
    focus: ["Marine ecology", "Research", "Advisory"],
  },
];

export const cohorts: Cohort[] = [
  "On-island team",
  "Board of Directors",
  "Scientific Advisory Board",
];

export const focusAreas = Array.from(
  new Set(people.flatMap((person) => person.focus)),
).sort((a, b) => a.localeCompare(b));
