export type Cohort =
  | "On-island team"
  | "Board of Directors"
  | "Scientific Advisory Board";

export type Person = {
  id: string;
  name: string;
  role: string;
  cohort: Cohort;
  image: string;
  href: string;
  summary: string;
  focus: string[];
  featured?: boolean;
};

const site = "https://www.tetiaroasociety.org";

const image = (path: string) => `${site}${path}`;
const profile = (path: string) => `${site}${path}`;

const staffSummary =
  "Keeps the daily work of the atoll moving across conservation, education, visitor learning, and field operations.";
const boardSummary =
  "Provides governance, institutional memory, and cross-sector stewardship for Tetiaroa Society's long-term resilience.";
const advisorySummary =
  "Advises the science program so field observations, restoration choices, and research partnerships stay rigorous.";

export const people: Person[] = [
  {
    id: "tj-tate",
    name: "Tj Tate",
    role: "Chief Executive Officer",
    cohort: "On-island team",
    image: image("/sites/default/files/styles/square_400/public/2025-08/TJ-Tate.jpg.webp?itok=ygX3GsGZ"),
    href: profile("/tj-tate"),
    summary:
      "Leads the society's next chapter, connecting field work, partnerships, education, and donor support into one operating rhythm.",
    focus: ["Leadership", "Partnerships", "Strategy"],
    featured: true,
  },
  {
    id: "julien-castel",
    name: "Julien Castel",
    role: "Chief Financial Officer",
    cohort: "On-island team",
    image: image("/sites/default/files/styles/square_400/public/2026-06/Julien%20Castel%20Portrait.jpeg.webp?itok=IpW1lfQo"),
    href: profile("/julien-castel"),
    summary: "Bio forthcoming.",
    focus: ["Leadership", "Finance"],
  },
  {
    id: "jayna-devore",
    name: "Dr. Jayna DeVore",
    role: "Director of Conservation, Science & Education",
    cohort: "On-island team",
    image: image("/sites/default/files/styles/square_400/public/2026-06/Jayna%20and%20bird%20sq_0.jpg.webp?itok=twDvGrfn"),
    href: profile("/dr-jayna-devore"),
    summary: "Bio forthcoming.",
    focus: ["Leadership", "Conservation", "Science", "Education"],
  },
  {
    id: "giulia-mouly",
    name: "Giulia Mouly",
    role: "Director of Operations",
    cohort: "On-island team",
    image: image("/sites/default/files/styles/square_400/public/2026-06/Giulia%20Mouly%20Portrait.jpeg.webp?itok=xj3z1wo5"),
    href: profile("/giulia-mouly"),
    summary:
      "Connects people, place, and purpose through field station operations, hospitality, partnerships, and sustainability.",
    focus: ["Operations", "Bailey Field Station", "Partnerships"],
  },
  {
    id: "hinanui-robson",
    name: "Hinanui Joan Robson",
    role: "Science and Conservation Coordinator",
    cohort: "On-island team",
    image: image("/sites/default/files/styles/square_400/public/2025-08/Hinanui%20Robson.jpg.webp?itok=Ot5S6IQ-"),
    href: profile("/hinanui-robson"),
    summary:
      "Coordinates research activity on the atoll, helping field teams, visiting scientists, and local knowledge meet cleanly.",
    focus: ["Science", "Research", "Field operations"],
    featured: true,
  },
  {
    id: "tihoni-maire",
    name: "Tihoni Maire",
    role: "Chief Naturalist",
    cohort: "On-island team",
    image: image("/sites/default/files/styles/square_400/public/2024-06/tihoni2024.jpg.webp?itok=tVS07kMJ"),
    href: profile("/tihoni-maire"),
    summary:
      "Leads guide experiences that translate the atoll's wildlife, history, and conservation work for visitors.",
    focus: ["Guides", "Culture", "Visitor learning"],
    featured: true,
  },
  {
    id: "vaitea-izal",
    name: "Vaitea Izal",
    role: "Bailey Field Station Manager",
    cohort: "On-island team",
    image: image("/sites/default/files/styles/square_400/public/2025-07/vaitea-izal-2025.JPEG.webp?itok=0wTKxA2L"),
    href: profile("/vaitea-izal"),
    summary:
      "Keeps the Ecostation ready for the researchers, students, and partners who turn the atoll into a living laboratory.",
    focus: ["Ecostation", "Operations", "Research"],
    featured: true,
  },
  {
    id: "hereiti-lelong",
    name: "Elena Hereiti Lelong",
    role: "Communications Manager",
    cohort: "On-island team",
    image: image("/sites/default/files/styles/square_400/public/2026-04/elena-lelong-communications.jpeg.webp?itok=hHbmdmq6"),
    href: profile("/hereiti-lelong"),
    summary:
      "Shapes the public story of the work, from field updates and education moments to the society's wider voice.",
    focus: ["Communications", "Storytelling", "Community"],
  },
  {
    id: "ngnahina-moua",
    name: "Ngnahina Moua",
    role: "Education & Cultural Coordinator",
    cohort: "On-island team",
    image: image("/sites/default/files/styles/square_400/public/2026-03/Ngnahina.jpg.webp?itok=_zZResUd"),
    href: profile("/ngnahina-moua"),
    summary:
      "Builds education and cultural programs that connect Polynesian students with Polynesian science and stewardship.",
    focus: ["Education", "Culture", "Community"],
    featured: true,
  },
  {
    id: "kealoha-wilkes",
    name: "Kealoha Wilkes",
    role: "Naturalist",
    cohort: "On-island team",
    image: image("/sites/default/files/styles/square_400/public/2024-07/Kealoha-Wilkes2.jpg.webp?itok=MYtxye9o"),
    href: profile("/kealoha-wilkes"),
    summary: staffSummary,
    focus: ["Guides", "Visitor learning", "Culture"],
  },
  {
    id: "hugo-torres",
    name: "Hugo Torres",
    role: "Naturalist",
    cohort: "On-island team",
    image: image("/sites/default/files/styles/square_400/public/2025-08/Hugo%20Torres.jpg.webp?itok=dNp1dE-L"),
    href: profile("/hugo-torres"),
    summary: staffSummary,
    focus: ["Guides", "Visitor learning", "Field operations"],
  },
  {
    id: "hina-patii",
    name: "Hina Patii",
    role: "Naturalist",
    cohort: "On-island team",
    image: image("/sites/default/files/styles/square_400/public/2025-08/Hina%20Patii.jpg.webp?itok=kc7G1PS-"),
    href: profile("/hina-patii"),
    summary: staffSummary,
    focus: ["Guides", "Visitor learning", "Culture"],
  },
  {
    id: "tekura-ung",
    name: "Tekura Ung",
    role: "Naturalist",
    cohort: "On-island team",
    image: image("/sites/default/files/styles/square_400/public/2024-08/tekura.jpg.webp?itok=O4IzlAf9"),
    href: profile("/tekura-ung"),
    summary: staffSummary,
    focus: ["Guides", "Visitor learning", "Culture"],
  },
  {
    id: "thierry-sommer",
    name: "Thierry Sommer",
    role: "Naturalist",
    cohort: "On-island team",
    image: image("/sites/default/files/styles/square_400/public/2025-08/Thierry%20Sommer.jpg.webp?itok=1YnIdXD6"),
    href: profile("/thierry-sommer"),
    summary: staffSummary,
    focus: ["Guides", "Visitor learning", "Field operations"],
  },
  {
    id: "maxime-courroux",
    name: "Maxime Courroux",
    role: "Naturalist",
    cohort: "On-island team",
    image: image("/sites/default/files/styles/square_400/public/2026-03/Maxime.JPG.webp?itok=1h3uFdYH"),
    href: profile("/maxime-courroux"),
    summary: staffSummary,
    focus: ["Guides", "Visitor learning", "Field operations"],
  },
  {
    id: "romain-clervoy",
    name: "Romain Clervoy",
    role: "Dive Operations Manager",
    cohort: "On-island team",
    image: image("/sites/default/files/styles/square_400/public/2024-04/RomainClervoy.jpg.webp?itok=kuXtXq0G"),
    href: profile("/romain-clervoy"),
    summary:
      "Oversees dive operations that help people encounter the reef while respecting the atoll's rules and rhythms.",
    focus: ["Dive operations", "Safety", "Visitor learning"],
    featured: true,
  },
  {
    id: "lusiano-kolokilagi",
    name: "Lusiano Kolokilagi",
    role: "Ranger",
    cohort: "On-island team",
    image: image("/sites/default/files/styles/square_400/public/2024-07/lusiano.jpg.webp?itok=7fZrAKag"),
    href: profile("/lusiano-kolokilagi"),
    summary: staffSummary,
    focus: ["Rangers", "Field operations", "Conservation"],
  },
  {
    id: "tuterai-apuarii",
    name: "Tuterai Apuarii",
    role: "Ranger",
    cohort: "On-island team",
    image: image("/sites/default/files/styles/square_400/public/2023-05/tuterai.jpg.webp?itok=des5lhCs"),
    href: profile("/tuterai-apuarii"),
    summary: staffSummary,
    focus: ["Rangers", "Field operations", "Conservation"],
  },
  {
    id: "jean-paul-chongue",
    name: "Jean Paul Chongue",
    role: "Ranger",
    cohort: "On-island team",
    image: image("/sites/default/files/styles/square_400/public/2026-03/Jean%20Paul%20Chongue.jpg.webp?itok=MQS-TtoO"),
    href: profile("/jean-paul-chongue"),
    summary: staffSummary,
    focus: ["Rangers", "Field operations", "Conservation"],
  },
  {
    id: "carol-ann-raydon",
    name: "Carol Ann Raydon",
    role: "Web Designer/Developer",
    cohort: "On-island team",
    image: image("/sites/default/files/styles/square_400/public/2026-03/CarolTS.jpg.webp?itok=7sUOoN2H"),
    href: profile("/carol-ann-raydon"),
    summary: staffSummary,
    focus: ["Digital", "Communications", "Storytelling"],
  },
  {
    id: "david-seeley",
    name: "David Seeley",
    role: "Treasurer",
    cohort: "Board of Directors",
    image: image("/sites/default/files/styles/square_400/public/2024-07/David-Seeley.jpg.webp?itok=lBtxYDmS"),
    href: profile("/david-seeley"),
    summary: boardSummary,
    focus: ["Governance", "Strategy", "Stewardship"],
  },
  {
    id: "neil-davies-board",
    name: "Neil Davies",
    role: "Board Member",
    cohort: "Board of Directors",
    image: image("/sites/default/files/styles/square_400/public/2024-07/Davies_Neil_2.jpeg.webp?itok=gmlG9zcE"),
    href: profile("/neil-davies"),
    summary: boardSummary,
    focus: ["Governance", "Science", "Research"],
  },
  {
    id: "stan-rowland",
    name: "Stan Rowland",
    role: "Secretary",
    cohort: "Board of Directors",
    image: image("/sites/default/files/styles/square_400/public/2024-08/Stan-Rowland.jpeg.webp?itok=M2H-6ySf"),
    href: profile("/stan-rowland"),
    summary: boardSummary,
    focus: ["Governance", "Stewardship", "Strategy"],
  },
  {
    id: "cecile-gaspar-board",
    name: "Cecile Gaspar",
    role: "Board Member",
    cohort: "Board of Directors",
    image: image("/sites/default/files/styles/square_400/public/2024-07/Cecile-Gaspar.jpg.webp?itok=cqn9H2Ry"),
    href: profile("/cecile-gaspar"),
    summary: boardSummary,
    focus: ["Governance", "Conservation", "Science"],
  },
  {
    id: "ed-begley",
    name: "Ed Begley",
    role: "Board Member",
    cohort: "Board of Directors",
    image: image("/sites/default/files/styles/square_400/public/2024-07/Ed-Begley_0.JPG.webp?itok=OBlPu4oZ"),
    href: profile("/ed-begley"),
    summary: boardSummary,
    focus: ["Governance", "Advocacy", "Stewardship"],
  },
  {
    id: "richard-bailey",
    name: "Richard Bailey",
    role: "Board Chairman",
    cohort: "Board of Directors",
    image: image("/sites/default/files/styles/square_400/public/2024-07/Richard-Bailey_1.jpeg.webp?itok=mcrC_ZB8"),
    href: profile("/richard-bailey"),
    summary: boardSummary,
    focus: ["Governance", "Partnerships", "Stewardship"],
  },
  {
    id: "larry-dressler",
    name: "Larry Dressler",
    role: "Board Member",
    cohort: "Board of Directors",
    image: image("/sites/default/files/styles/square_400/public/2017-01/larry-dressler.jpg.webp?itok=VxvQv4JG"),
    href: profile("/larry-dressler"),
    summary: boardSummary,
    focus: ["Governance", "Strategy", "Stewardship"],
  },
  {
    id: "avra-douglas",
    name: "Avra Douglas",
    role: "Board Member",
    cohort: "Board of Directors",
    image: image("/sites/default/files/styles/square_400/public/2024-07/avra-douglas.jpg.webp?itok=M0d6z2_U"),
    href: profile("/avra-douglas"),
    summary: boardSummary,
    focus: ["Governance", "Community", "Stewardship"],
  },
  {
    id: "mike-medavoy",
    name: "Mike Medavoy",
    role: "Board Member",
    cohort: "Board of Directors",
    image: image("/sites/default/files/styles/square_400/public/2024-07/Mike-Medavoy.JPG.webp?itok=POho-mfX"),
    href: profile("/mike-medavoy"),
    summary: boardSummary,
    focus: ["Governance", "Storytelling", "Advocacy"],
  },
  {
    id: "daniel-kammen-board",
    name: "Daniel Kammen",
    role: "Board Member",
    cohort: "Board of Directors",
    image: image("/sites/default/files/styles/square_400/public/2024-07/Dan-Kammen.jpeg.webp?itok=zSqcb3cq"),
    href: profile("/daniel-kammen"),
    summary: boardSummary,
    focus: ["Governance", "Climate", "Science"],
  },
  {
    id: "benjamin-anderson",
    name: "Benjamin Anderson",
    role: "Board Member",
    cohort: "Board of Directors",
    image: image("/sites/default/files/styles/square_400/public/2024-07/benjamin-anderson2.jpg.webp?itok=xxWKSXcC"),
    href: profile("/benjamin-anderson"),
    summary: boardSummary,
    focus: ["Governance", "Strategy", "Partnerships"],
  },
  {
    id: "costas-christ",
    name: "Costas Christ",
    role: "Board Member",
    cohort: "Board of Directors",
    image: image("/sites/default/files/styles/square_400/public/2024-07/Costas-Christ.jpg.webp?itok=NUDymiw4"),
    href: profile("/costas-christ"),
    summary: boardSummary,
    focus: ["Governance", "Sustainable travel", "Stewardship"],
  },
  {
    id: "hinano-murphy",
    name: "Hinano Murphy",
    role: "Board Member",
    cohort: "Board of Directors",
    image: image("/sites/default/files/styles/square_400/public/2024-07/Hinano-Murphy.jpg.webp?itok=i4PhvFU5"),
    href: profile("/hinano-murphy"),
    summary: boardSummary,
    focus: ["Governance", "Culture", "Education"],
  },
  {
    id: "carl-swanes",
    name: "Carl Swanes",
    role: "Board Member",
    cohort: "Board of Directors",
    image: image("/sites/default/files/styles/square_400/public/2018-10/carl-swanes_0.jpg.webp?itok=BNTSR2O-"),
    href: profile("/carl-swanes"),
    summary: boardSummary,
    focus: ["Governance", "Strategy", "Stewardship"],
  },
  {
    id: "rebecca-brando",
    name: "Rebecca Brando",
    role: "Board Member",
    cohort: "Board of Directors",
    image: image("/sites/default/files/styles/square_400/public/2024-07/Rebecca-Brando.jpeg.webp?itok=JPMec9GR"),
    href: profile("/rebecca-brando"),
    summary: boardSummary,
    focus: ["Governance", "Legacy", "Stewardship"],
  },
  {
    id: "rick-hess",
    name: "Rick Hess",
    role: "Board Member",
    cohort: "Board of Directors",
    image: image("/sites/default/files/styles/square_400/public/2024-07/Rick-Hess.jpg.webp?itok=aZ-j-Cdf"),
    href: profile("/rick-hess"),
    summary: boardSummary,
    focus: ["Governance", "Strategy", "Stewardship"],
  },
  {
    id: "susan-neisloss",
    name: "Susan Neisloss",
    role: "Vice Chair",
    cohort: "Board of Directors",
    image: image("/sites/default/files/styles/square_400/public/2025-09/Susan-Neisloss.jpg.webp?itok=eyHbLSTu"),
    href: profile("/susan-neisloss"),
    summary: boardSummary,
    focus: ["Governance", "Advocacy", "Stewardship"],
  },
  {
    id: "heather-grenier",
    name: "Heather Grenier",
    role: "Board Member",
    cohort: "Board of Directors",
    image: image("/sites/default/files/styles/square_400/public/2025-08/Heather-Grenier.jpg.webp?itok=vCjsSbiA"),
    href: profile("/heather-grenier"),
    summary: boardSummary,
    focus: ["Governance", "Partnerships", "Stewardship"],
  },
  {
    id: "michael-v-lewis",
    name: "Michael V Lewis",
    role: "Board Member",
    cohort: "Board of Directors",
    image: image("/sites/default/files/styles/square_400/public/2026-05/MVL%20Headshot.jpg.webp?itok=n9lHS9PR"),
    href: profile("/michael-v-lewis"),
    summary: boardSummary,
    focus: ["Governance", "Strategy", "Partnerships"],
  },
  {
    id: "neil-davies-advisory",
    name: "Neil Davies",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: image("/sites/default/files/styles/square_400/public/2024-07/Davies_Neil_2.jpeg.webp?itok=gmlG9zcE"),
    href: profile("/neil-davies"),
    summary: advisorySummary,
    focus: ["Science", "Research", "Advisory"],
  },
  {
    id: "sylvia-earle",
    name: "Sylvia Earle",
    role: "Scientific Advisor Emeritus",
    cohort: "Scientific Advisory Board",
    image: image("/sites/default/files/styles/square_400/public/2017-01/sylvia-earle.jpg.webp?itok=1X07zuZf"),
    href: profile("/sylvia-earle"),
    summary: advisorySummary,
    focus: ["Ocean science", "Advisory", "Conservation"],
  },
  {
    id: "billie-swalla",
    name: "Billie Swalla",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: image("/sites/default/files/styles/square_400/public/2017-01/billie-swalla.jpg.webp?itok=okdi5OMB"),
    href: profile("/billie-swalla"),
    summary: advisorySummary,
    focus: ["Science", "Research", "Advisory"],
  },
  {
    id: "annaig-le-guen",
    name: "Annaig Le Guen",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: image("/sites/default/files/styles/square_400/public/2020-04/id%20ALG.png.webp?itok=BDjcV2tl"),
    href: profile("/annaig-le-guen"),
    summary: advisorySummary,
    focus: ["Culture", "Research", "Advisory"],
  },
  {
    id: "benoit-stoll",
    name: "Benoit Stoll",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: image("/sites/default/files/styles/square_400/public/2020-04/benoit-stoll.JPG.webp?itok=FwjnlVV1"),
    href: profile("/benoit-stoll"),
    summary: advisorySummary,
    focus: ["Science", "Research", "Advisory"],
  },
  {
    id: "beth-gardner",
    name: "Beth Gardner",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: image("/sites/default/files/styles/square_400/public/2020-04/beth-gardner.png.webp?itok=Ua8z470Y"),
    href: profile("/beth-gardner"),
    summary: advisorySummary,
    focus: ["Science", "Research", "Advisory"],
  },
  {
    id: "cecile-gaspar-advisory",
    name: "Cecile Gaspar",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: image("/sites/default/files/styles/square_400/public/2024-07/Cecile-Gaspar.jpg.webp?itok=cqn9H2Ry"),
    href: profile("/cecile-gaspar"),
    summary: advisorySummary,
    focus: ["Conservation", "Science", "Advisory"],
  },
  {
    id: "chris-meyer",
    name: "Chris Meyer",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: image("/sites/default/files/styles/square_400/public/2017-01/chris-meyer.jpg.webp?itok=4crsP5zT"),
    href: profile("/chris-meyer"),
    summary: advisorySummary,
    focus: ["Biodiversity", "Research", "Advisory"],
  },
  {
    id: "daniel-kammen-advisory",
    name: "Daniel Kammen",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: image("/sites/default/files/styles/square_400/public/2024-07/Dan-Kammen.jpeg.webp?itok=zSqcb3cq"),
    href: profile("/daniel-kammen"),
    summary: advisorySummary,
    focus: ["Climate", "Energy", "Advisory"],
  },
  {
    id: "guillaume-molle",
    name: "Guillaume Molle",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: image("/sites/default/files/styles/square_400/public/2020-04/G.Molle_.jpg.webp?itok=l_B00KU_"),
    href: profile("/guillaume-molle"),
    summary: advisorySummary,
    focus: ["Culture", "Research", "Advisory"],
  },
  {
    id: "herve-bossin",
    name: "Herve Bossin",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: image("/sites/default/files/styles/square_400/public/2017-01/herve-boissin.jpg.webp?itok=g5rEMOy7"),
    href: profile("/herve-boissin"),
    summary: advisorySummary,
    focus: ["Biosecurity", "Research", "Advisory"],
  },
  {
    id: "hillary-young",
    name: "Hillary Young",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: image("/sites/default/files/styles/square_400/public/2020-04/Hillary-Young.png.webp?itok=IRAy-H7V"),
    href: profile("/hillary-young"),
    summary: advisorySummary,
    focus: ["Ecology", "Research", "Advisory"],
  },
  {
    id: "james-russell",
    name: "James Russell",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: image("/sites/default/files/styles/square_400/public/2017-01/james-russell.jpg.webp?itok=g4ZFn6m6"),
    href: profile("/james-russell"),
    summary: advisorySummary,
    focus: ["Restoration", "Research", "Advisory"],
  },
  {
    id: "jean-yves-meyer",
    name: "Jean-Yves Hiro Meyer",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: image("/sites/default/files/styles/square_400/public/2017-01/jean-yves-meyer.jpg.webp?itok=fFcIMlHp"),
    href: profile("/jean-yves-meyer"),
    summary: advisorySummary,
    focus: ["Botany", "Research", "Advisory"],
  },
  {
    id: "judy-lemus",
    name: "Judy Lemus",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: image("/sites/default/files/styles/square_400/public/2020-04/Judy-Lemus.jpeg.webp?itok=T7V1TyL1"),
    href: profile("/judy-lemus"),
    summary: advisorySummary,
    focus: ["Education", "Research", "Advisory"],
  },
  {
    id: "mayalen-zubia",
    name: "Mayalen Zubia",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: image("/sites/default/files/styles/square_400/public/2020-04/Mayalen-Zubia.jpg.webp?itok=TNZtXj7o"),
    href: profile("/mayalen-zubia"),
    summary: advisorySummary,
    focus: ["Marine ecology", "Research", "Advisory"],
  },
  {
    id: "patrick-kirch",
    name: "Patrick Kirch",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: image("/sites/default/files/styles/square_400/public/2017-01/patrick-kirch.jpg.webp?itok=EgQakeGZ"),
    href: profile("/patrick-kirch"),
    summary: advisorySummary,
    focus: ["Culture", "Research", "Advisory"],
  },
  {
    id: "robert-carpenter",
    name: "Robert Carpenter",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: image("/sites/default/files/styles/square_400/public/2017-01/robert-carpenter.png.webp?itok=Jf8WfsC2"),
    href: profile("/robert-carpenter"),
    summary: advisorySummary,
    focus: ["Marine ecology", "Research", "Advisory"],
  },
  {
    id: "yadvinder-malhi",
    name: "Yadvinder Malhi",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: image("/sites/default/files/styles/square_400/public/2020-04/Malhi%20Tambopata.jpg.webp?itok=YLMuXVgC"),
    href: profile("/yadvinder-malhi"),
    summary: advisorySummary,
    focus: ["Climate", "Ecology", "Advisory"],
  },
  {
    id: "ruth-gates",
    name: "Ruth Gates",
    role: "Scientific Advisor",
    cohort: "Scientific Advisory Board",
    image: image("/sites/default/files/styles/square_400/public/2017-01/ruth-gates.png.webp?itok=ZfSjvEp5"),
    href: profile("/ruth-gates"),
    summary: advisorySummary,
    focus: ["Coral", "Research", "Advisory"],
  },
  {
    id: "serge-planes",
    name: "Serge Planes",
    role: "Scientific Advisor Emeritus",
    cohort: "Scientific Advisory Board",
    image: image("/sites/default/files/styles/square_400/public/2017-01/serge-planes.jpg.webp?itok=VpQk8qFg"),
    href: profile("/serge-planes"),
    summary: advisorySummary,
    focus: ["Marine ecology", "Research", "Advisory"],
  },
];

export const cohorts: Cohort[] = [
  "On-island team",
  "Board of Directors",
  "Scientific Advisory Board",
];

export const focusAreas = Array.from(
  new Set(people.flatMap((person) => person.focus)),
).sort((a, b) => a.localeCompare(b));
