export const atollCopy = {
  en: {
    atoll: "Our Atoll", guide: "Species", eyebrow: "Tetiaroa · French Polynesia",
    hubDescription: "Discover Tetiaroa’s species, geology and seawater air conditioning.",
    speciesDestinationDescription: "Plants and animals, from shore to open ocean.",
    geologyDestinationDescription: "How an atoll takes shape.",
    swacDestinationDescription: "Air conditioning with cold seawater.",
    aboutAtoll: "About the atoll", ourWork: "Our work", filters: "Filters", allSpecies: "All", backToResults: "Back to results", profileDetails: "About this species", profileMedia: "Audio and video",
    compactIntro: "Plants and animals of Tetiaroa and French Polynesia.",
    exploreTitle: "From the forest to the open sea", exploreDescription: "Explore Tetiaroa’s motu, lagoon and reef, then see how the atoll took shape beneath them.",
    guideTitle: "Species of Tetiaroa and French Polynesia", guideDescription: "Find plants and animals by name, species group or habitat. Browse photographs, local names and species profiles from Tetiaroa and French Polynesia.",
    browse: "Browse the guide", browseAll: "Browse all entries", habitatsEyebrow: "From the canopy to the open sea", habitatsTitle: "Three habitats to explore",
    habitatLink: "Explore this habitat", categoriesEyebrow: "The nature guide", categoriesTitle: "Get to know the species", categoriesIntro: "Choose a group to explore its photographs, names and natural history.",
    entryCount: "guide entries", countNote: "The guide includes species from Tetiaroa and elsewhere in French Polynesia. Local occurrence is noted where documented.",
    searchLabel: "Search species", searchPlaceholder: "A common, scientific or local name", search: "Search", category: "Species group", subgroup: "Subgroup", habitat: "Habitat",
    allCategories: "All species groups", allSubgroups: "All subgroups", allHabitats: "All habitats", clear: "Clear all", result: "result", results: "results", showing: "Showing", of: "of", previous: "Previous", next: "Next", page: "Page",
    noResults: "No matching entries", noResultsDescription: "Try another name, or widen your search by clearing a filter.", noEntries: "The guide is being prepared", noEntriesDescription: "The first profiles will appear here when they are published.",
    searchHint: "English, French, scientific and local names all work. Accents and apostrophes are optional.",
    foundationEyebrow: "Below the surface", foundationTitle: "An island built by life", geologyTitle: "How an atoll is made", geologyDescription: "Follow the volcanic foundations, the rising reef and the changing sea that shaped Tetiaroa.", geologyLink: "Explore the geology",
    swacTitle: "Cooling from the deep ocean", swacDescription: "Follow cold seawater from the ocean depths to the system that cools buildings on Tetiaroa.", swacLink: "Discover ocean cooling",
    readingEyebrow: "Stories from the field", readingTitle: "Keep exploring", readStory: "Read the story", backToGuide: "Back to the guide", profile: "Species profile", localNames: "Local names", otherNames: "Other names", namesNote: "Regional names", occurrence: "Where it occurs", plantFacts: "Plant facts", family: "Family", biogeographicalStatus: "Biogeographical status", lifeForm: "Life form", abundance: "Abundance", ecosystem: "Ecosystem", gallery: "Photographs", listen: "Listen", watch: "Watch", resources: "Sources and further reading", download: "Open document", openMedia: "Open media", imageUnavailable: "No photograph available", breadcrumbs: "Breadcrumbs", pagination: "Guide pages", skip: "Skip to content", photo: "Photo", license: "License", imageAlt: "Tetiaroa, its lagoon and surrounding reef", home: "Home",
  },
  fr: {
    atoll: "Notre atoll", guide: "Espèces", eyebrow: "Tetiaroa · Polynésie française",
    hubDescription: "Découvrez les espèces, la géologie et la climatisation à l’eau de mer de Tetiaroa.",
    speciesDestinationDescription: "Les plantes et les animaux, du rivage au large.",
    geologyDestinationDescription: "Comment se forme un atoll.",
    swacDestinationDescription: "La climatisation à l’eau de mer froide.",
    aboutAtoll: "Découvrir l’atoll", ourWork: "Nos actions", filters: "Filtres", allSpecies: "Tous", backToResults: "Retour aux résultats", profileDetails: "Portrait de l’espèce", profileMedia: "Sons et vidéos",
    compactIntro: "Les plantes et les animaux de Tetiaroa et de Polynésie française.",
    exploreTitle: "De la forêt au grand large", exploreDescription: "Découvrez les motu, le lagon et le récif de Tetiaroa, puis les origines de l’atoll.",
    guideTitle: "Espèces de Tetiaroa et de Polynésie française", guideDescription: "Recherchez les plantes et les animaux par nom, groupe d’espèces ou milieu. Consultez les photos, les noms locaux et les fiches de Tetiaroa et de Polynésie française.",
    browse: "Parcourir le guide", browseAll: "Voir toutes les fiches", habitatsEyebrow: "De la canopée au grand large", habitatsTitle: "Trois milieux à explorer",
    habitatLink: "Explorer ce milieu", categoriesEyebrow: "Le guide nature", categoriesTitle: "Découvrez les espèces", categoriesIntro: "Choisissez un groupe pour découvrir ses photographies, ses noms et son histoire naturelle.",
    entryCount: "fiches du guide", countNote: "Le guide réunit des espèces de Tetiaroa et d’ailleurs en Polynésie française. Leur présence sur l’atoll est précisée lorsqu’elle est documentée.",
    searchLabel: "Rechercher une espèce", searchPlaceholder: "Un nom commun, scientifique ou local", search: "Rechercher", category: "Groupe d’espèces", subgroup: "Sous-groupe", habitat: "Milieu",
    allCategories: "Tous les groupes", allSubgroups: "Tous les sous-groupes", allHabitats: "Tous les milieux", clear: "Tout effacer", result: "résultat", results: "résultats", showing: "Affichage", of: "sur", previous: "Précédent", next: "Suivant", page: "Page",
    noResults: "Aucune fiche trouvée", noResultsDescription: "Essayez un autre nom ou élargissez votre recherche en retirant un filtre.", noEntries: "Le guide est en préparation", noEntriesDescription: "Les premières fiches apparaîtront ici dès leur publication.",
    searchHint: "Noms français, anglais, scientifiques ou locaux : les accents et apostrophes sont facultatifs.",
    foundationEyebrow: "Sous la surface", foundationTitle: "Une île bâtie par le vivant", geologyTitle: "Comment naît un atoll", geologyDescription: "Du socle volcanique au récif corallien, suivez les transformations qui ont façonné Tetiaroa.", geologyLink: "Explorer la géologie",
    swacTitle: "La fraîcheur vient des profondeurs", swacDescription: "Suivez l’eau de mer froide depuis les profondeurs jusqu’au système qui rafraîchit les bâtiments de Tetiaroa.", swacLink: "Découvrir la climatisation marine",
    readingEyebrow: "Histoires de terrain", readingTitle: "Poursuivre la découverte", readStory: "Lire l’article", backToGuide: "Retour au guide", profile: "Fiche espèce", localNames: "Noms locaux", otherNames: "Autres noms", namesNote: "Noms régionaux", occurrence: "Répartition", plantFacts: "Repères botaniques", family: "Famille", biogeographicalStatus: "Statut biogéographique", lifeForm: "Forme biologique", abundance: "Abondance", ecosystem: "Écosystème", gallery: "Photographies", listen: "Écouter", watch: "Regarder", resources: "Sources et lectures complémentaires", download: "Ouvrir le document", openMedia: "Ouvrir le média", imageUnavailable: "Photographie indisponible", breadcrumbs: "Fil d’Ariane", pagination: "Pages du guide", skip: "Aller au contenu", photo: "Photo", license: "Licence", imageAlt: "Tetiaroa, son lagon et sa couronne récifale", home: "Accueil",
  },
} as const;
