export const adventureCopy = {
  eyebrow: "Your dive with HONU",
  title: "Dive with HONU",
  intro:
    "Steer HONU from the reef into open water. Look for animals among the coral, then try the lights and sonar farther out.",
  startTitle: "Come sit by the dome.",
  startBody:
    "Start beside the reef. Steer around the coral to find the animals that live here.",
  start: "Start my dive",
  exploreHint: "Tap the water or use arrow keys to head beyond the reef.",
  supportTitle: "Help us find out what lives below.",
  supportBody:
    "From HONU’s dome, researchers can observe marine life beneath the surface. Support Tetiaroa Society’s work to study the ocean and bring those discoveries into lessons that students can explore for themselves.",
};

export const neighbors = [
  {
    id: "coral",
    number: "01",
    name: "Coral colony",
    route: "Reef floor",
    clue: "Look along the reef floor",
    photo: {
      src: "/honu-photos/coral.webp",
      alt: "A close view of branching staghorn coral with small polyps extending from its surface.",
      width: 1200,
      height: 800,
      credit: "Ryan Hagerty / USFWS",
      sourceUrl: "https://www.fws.gov/media/close-staghorn-coral-palmyra-atoll",
      license: "Public domain",
      licenseUrl: "https://www.fws.gov/media/close-staghorn-coral-palmyra-atoll",
    },
    hint: "Look down at the branching coral.",
    after: "Keep exploring above the coral.",
    action: "Explore the coral",
    title: "A colony of tiny animals.",
    fact: "This coral colony is made of tiny animals called polyps. Each polyp builds a hard skeleton of calcium carbonate. Over generations, stony coral skeletons form the reef.",
    subFact:
      "HONU’s dome lets researchers observe coral in place. Hold the sub above the branches to take a closer look without touching them.",
    tool: "Observation dome",
    source: "https://oceanservice.noaa.gov/facts/coral.html",
    sourceLabel: "More about corals · NOAA",
  },
  {
    id: "butterflyfish",
    number: "02",
    name: "Butterflyfish",
    route: "Reef garden",
    clue: "A fish above the coral",
    photo: {
      src: "/honu-photos/butterflyfish.webp",
      alt: "Yellow raccoon butterflyfish with black eye bands swimming above a coral reef.",
      width: 1200,
      height: 800,
      credit: "Ryan Hagerty / USFWS",
      sourceUrl: "https://www.fws.gov/media/raccoon-butterflyfish-4",
      license: "Public domain",
      licenseUrl: "https://www.fws.gov/media/raccoon-butterflyfish-4",
    },
    hint: "Look for the small fish above the coral.",
    after: "Keep exploring the reef.",
    action: "Meet the butterflyfish",
    title: "What butterflyfish eat.",
    fact: "Butterflyfish have rows of tiny, comb-like teeth. Some eat coral polyps, while others pick off small animals or feed on plankton in the water.",
    subFact:
      "Hold HONU steady and watch the fish without chasing it. The thrusters let the pilot adjust position with small movements.",
    tool: "Thrusters",
    source:
      "https://www.waikikiaquarium.org/experience/animal-guide/fishes/butterflyfishes/raccoon-butterflyfish/",
    sourceLabel: "More about butterflyfish · Waikīkī Aquarium",
  },
  {
    id: "turtle",
    number: "03",
    name: "Green sea turtle",
    route: "Reef garden",
    clue: "Follow the flippers",
    photo: {
      src: "/honu-photos/turtle.webp",
      alt: "A green sea turtle swimming above a rocky reef in the Galápagos.",
      width: 1200,
      height: 900,
      credit: "MasterfulNerd",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Green_Sea_Turtle_Swimming_in_the_Gal%C3%A1pagos.jpg",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
    hint: "Near the surface. Hold steady and watch the turtle pass.",
    after: "Let the turtle swim on. Head beyond the reef.",
    action: "Meet the turtle",
    title: "One more breath, then back below.",
    fact: "Those flippers belong in the water, but a green sea turtle’s lungs need air. Watch it glide past the reef. Sooner or later, it must head to the surface for another breath.",
    subFact:
      "Ease off and let the turtle pass. HONU’s thrusters help the pilot move through the water or hold a position while researchers watch an animal.",
    tool: "Thrusters",
    source: "https://www.fisheries.noaa.gov/species/green-turtle",
    sourceLabel: "More about green sea turtles · NOAA",
  },
  {
    id: "octopus",
    number: "04",
    name: "Octopus",
    route: "Lower reef",
    clue: "Look near the rocks",
    photo: {
      src: "/honu-photos/octopus.webp",
      alt: "A day octopus blends into the reef, its mottled skin and textured head surrounding a visible orange eye.",
      width: 1200,
      height: 900,
      credit: "Rickard Zerpe",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Day_octopus_(Octopus_cyanea)_(35595531524).jpg",
      license: "CC BY 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    },
    hint: "Something hides in the rocks...",
    readyHint: "Hold steady for a closer look at the octopus.",
    after: "Head into open water when you’re ready.",
    action: "Meet the octopus",
    title: "How an octopus hides.",
    fact: "An octopus can change its skin’s color and texture to blend in with rocks or coral. Muscles control tiny sacs of pigment in the skin, helping it hide from predators.",
    subFact:
      "HONU’s lights help researchers see in dark water. You used them to spot the octopus near the reef floor.",
    tool: "Observation lights",
    source:
      "https://ocean.si.edu/ocean-life/invertebrates/how-octopuses-and-squids-change-color",
    sourceLabel: "More about octopus camouflage · Smithsonian Ocean",
  },
  {
    id: "jellyfish",
    number: "05",
    name: "Glowing jellyfish",
    route: "Lantern drift",
    clue: "Find a living light",
    photo: {
      src: "/honu-photos/jellyfish.webp",
      alt: "A crystal jellyfish with a transparent bell and fine trailing tentacles in blue water.",
      width: 1200,
      height: 900,
      credit: "Jim G",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:DSC26476,_Crystal_Jelly_(%22Aequorea_Victoria%22),_Monterey_Bay_Aquarium,_Monterey,_California,_USA_(5084797073).jpg",
      license: "CC BY 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    },
    hint: "A light shimmers in the darkness...",
    readyHint: "Watch the jellyfish drift past HONU.",
    after: "Keep going. A much bigger shape waits out in the blue.",
    action: "Meet the jellyfish",
    title: "That light belongs to the jellyfish.",
    fact: "Some jellyfish make light inside their bodies. A chemical reaction creates the glow—a process called bioluminescence.",
    subFact:
      "HONU’s lights help researchers see in dark water. With the lamps on, look at the jellyfish’s bell and trailing tentacles.",
    tool: "Observation lights",
    source: "https://oceanservice.noaa.gov/facts/biolum.html",
    sourceLabel: "More about bioluminescence · NOAA",
  },
  {
    id: "whale",
    number: "06",
    name: "Sperm whale",
    route: "The big blue",
    clue: "Find the shape in the blue",
    photo: {
      src: "/honu-photos/whale.webp",
      alt: "A sperm whale and her calf swimming together beneath the ocean surface.",
      width: 1200,
      height: 675,
      credit: "Gabriel Barathieu",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Mother_and_baby_sperm_whale.jpg",
      license: "CC BY-SA 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    },
    hint: "A shape in the deep...",
    readyHint: "There it is. Watch the whale move through the blue.",
    after: "Stay a while. Watch the whale slip through the blue.",
    action: "Meet the whale",
    title: "A whale hunting by sound.",
    fact: "A sperm whale fills its lungs at the surface before diving for food. In the dark, it makes clicks and listens for echoes to help find prey.",
    subFact:
      "HONU’s sonar sends sound through the water and picks up the echoes that return. When the view ahead gets dark, those echoes help researchers work out what lies beyond the dome.",
    tool: "Sonar",
    source: "https://www.fisheries.noaa.gov/species/sperm-whale",
    sourceLabel: "More about sperm whales · NOAA",
  },
] as const;

export type NeighborId = (typeof neighbors)[number]["id"];
